name: the new sunday
favicon: null
layout_spectrum: 0.7051947715226561
typography_spectrum: 0.8968459810130298
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.06855088518932462
  lightness: 0.7268120436929166
  saturation: 0.956861354643479
  rhythmicContrast: 0.6887918810825795
purpose: []
