name: the new sunday
favicon: null
layout_spectrum: 0.10573
typography_spectrum: 0.7902
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7fbfc'
    - '#1e1c11'
    - '#946751'
    - '#ac8d62'
    - '#c0c1c5'
  brandStrength: 0.125
  lightness: 0.875
  saturation: 0.4375
  rhythmicContrast: 0.6887918810825795
purpose: []
